apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: result
  labels:
    app: result
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - name: result
        image: prodopsio/vote:result
        command: ["nodemon", "server.js"]
        ports:
        - containerPort: 80
        - containerPort: 5858
          hostPort: 5858
---
apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    app: result
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: result
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: result
  labels:
    app: result
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: result
      http:
        paths:
        - backend:
            serviceName: result-service
            servicePort: web
