apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: vote
  labels:
    app: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - name: vote
        image: prodopsio/vote
        command: ["python", "app.py"]
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: vote-service
  labels:
    app: vote
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: vote
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: vote
  labels:
    app: vote
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: vote
      http:
        paths:
          - backend:
              serviceName: vote-service
              servicePort: web
