apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name:
  labels:
    app:
spec:
  replicas:
  selector:
    matchLabels:
      app:
  template:
    metadata:
      labels:
        app:
    spec:
      containers:
      - name:
        command:
        image:
        ports:
