apiVersion: apps/v1
kind:
metadata:
  name:
  labels:
    app:
spec:
  replicas:
  serviceName:
  selector:
    matchLabels:
      app:
  template:
    metadata:
      labels:
        app:
    spec:
      containers:
      - name:
        image:
        ports:
        - containerPort:
---
apiVersion: v1
kind: Service
metadata:
  name:
  labels:
    app:
spec:
  ports:
  - port:
    name:
  clusterIP: None
  selector:
    app:
