apiVersion: apps/v1
kind:
metadata:
  name:
  labels:
    app:
spec:
  replicas:
  selector:
    matchLabels:
      app:
  template:
    metadata:
      labels:
        app:
    spec:
      containers:
      - name:
        image:
        command:
        ports:
        - containerPort:
        - containerPort:
          hostPort:
---
apiVersion: v1
kind: Service
metadata:
  name:
  labels:
    app:
spec:
  ports:
  - port:
    name:
  clusterIP:
  selector:
    app:
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name:
  labels:
    app:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: result
      http:
        paths:
        - backend:
            serviceName:
            servicePort:
